name: My Workflow

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     
      - uses: actions/checkout@main
     
      # Replace all the occurrences of 'hello' with 'world' in all the txt files, 
      # excluding the node_modules folder
      - name: Replace multiple files
        uses: richardrigutins/replace-in-files@v2
        with:
          files: '**/*.*'
          search-text: 'hello'
          replacement-text: 'world'
          exclude: '.github/**'
          encoding: 'utf8'
          max-parallelism: 10
      
      # Replace all the occurrences of '{0}' with '42' in the README.md file
      - name: Replace single file
        uses: richardrigutins/replace-in-files@v2
        with:
          files: 'README.md'
          search-text: '{0}'
          replacement-text: '42'
