name: My Workflow

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     
      - uses: actions/checkout@main
     
      - name: Find and Replace
        uses: richardrigutins/replace-in-files@v2
        with:
          files: '**/*.py'
          search-text: 'hello'
          replacement-text: 'world'
          encoding: 'utf8'
          max-parallelism: 10
