name: My Workflow

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     
      - uses: actions/checkout@main
     
      # Replace all the occurrences of 'hello' with 'world' in all the txt files, 
      # excluding the node_modules folder
      - name: Replace multiple files
        uses: richardrigutins/replace-in-files@v2
        with:
          files: '**/*.*'
          search-text: 'hello'
          replacement-text: 'world'
          exclude: '.github/**'
          encoding: 'utf8'
          max-parallelism: 10
      
      # Replace all the occurrences of '{0}' with '42' in the README.md file
      - name: Replace single file
        uses: richardrigutins/replace-in-files@v2
        with:
          files: 'README.md'
          search-text: '{0}'
          replacement-text: '42'
      - id: commit_files
        name: Commit files  
        env:
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
        shell: bash
        run: |
                git config --local user.name "$GIT_USER_NAME"
                git config --local user.email "$GIT_USER_EMAIL"
                if ! git diff --exit-code; then
                    git add .
                    git commit -am "GH Action Files added $(date)"
                    git push -f origin main
                fi
